nginxConfigApi:
  image: gtrias/nginx-config-api
  ports:
    - 1337
  links:
    - mongo

mongo:
  image: mongo

nginx:
  image: nginx

dockerApiRegistrar:
  image: gtrias/docker-api-registrar
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - nginxConfigApi:nginxApi
