nginxConfigApi:
  image: gtrias/nginx-config-api
  ports:
    - 1337
  links:
    - mongo

mongo:
  image: mongo

nginx:
  image: nginx

dockerApiRegistrar:
  image: gtrias/docker-api-registrar
  links:
    - nginxConfigApi:nginxApi
